<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
class product extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Thêm dữ liệu vào bảng product
        DB::table('product')->insert([
            [
                'product_id' => 1,
                'name' => 'Smartphone',
                'description' => 'High-end smartphone',
                'color_id' => 1,
                'size_id' => 1,
                'created_by_user_id' => 1,
                'product_brand_id' => 1,
                'product_category_id' => 1,
                'price' => 799.99,
                'stock' => 50,
                'discount_id' => 1,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 2,
                'name' => 'Laptop',
                'description' => 'High-end Laptop',
                'color_id' => 1,
                'size_id' => 1,
                'created_by_user_id' => 1,
                'product_brand_id' => 1,
                'product_category_id' => 1,
                'price' => 799.99,
                'stock' => 50,
                'discount_id' => 1,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 3,
                'name' => 'Tablet',
                'description' => 'High-end Tablet',
                'color_id' => 1,
                'size_id' => 1,
                'created_by_user_id' => 1,
                'product_brand_id' => 1,
                'product_category_id' => 1,
                'price' => 799.99,
                'stock' => 50,
                'discount_id' => 1,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 4,
                'name' => 'Headphones',
                'description' => 'High-end Headphones',
                'color_id' => 1,
                'size_id' => 1,
                'created_by_user_id' => 1,
                'product_brand_id' => 1,
                'product_category_id' => 1,
                'price' => 799.99,
                'stock' => 50,
                'discount_id' => 1,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 5,
                'name' => 'Camera',
                'description' => 'High-end Camera',
                'color_id' => 1,
                'size_id' => 1,
                'created_by_user_id' => 1,
                'product_brand_id' => 1,
                'product_category_id' => 1,
                'price' => 799.99,
                'stock' => 50,
                'discount_id' => 1,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 6,
                'name' => 'Gaming Console',
                'description' => 'High-end Gaming Console',
                'color_id' => 1,
                'size_id' => 1,
                'created_by_user_id' => 1,
                'product_brand_id' => 1,
                'product_category_id' => 1,
                'price' => 799.99,
                'stock' => 50,
                'discount_id' => 1,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 7,
                'name' => 'Fitness Tracker',
                'description' => 'High-end Fitness Tracker',
                'color_id' => 1,
                'size_id' => 1,
                'created_by_user_id' => 1,
                'product_brand_id' => 1,
                'product_category_id' => 1,
                'price' => 799.99,
                'stock' => 50,
                'discount_id' => 1,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 8,
                'name' => 'Wireless Earbuds',
                'description' => 'High-end Wireless Earbuds',
                'color_id' => 1,
                'size_id' => 1,
                'created_by_user_id' => 1,
                'product_brand_id' => 1,
                'product_category_id' => 1,
                'price' => 799.99,
                'stock' => 50,
                'discount_id' => 1,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 9,
                'name' => 'Smartphone',
                'description' => 'High-end 4K TV',
                'color_id' => 1,
                'size_id' => 1,
                'created_by_user_id' => 1,
                'product_brand_id' => 1,
                'product_category_id' => 1,
                'price' => 799.99,
                'stock' => 50,
                'discount_id' => 1,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 10,
                'name' => 'Bluetooth Speaker',
                'description' => 'High-end Bluetooth Speaker',
                'color_id' => 1,
                'size_id' => 1,
                'created_by_user_id' => 1,
                'product_brand_id' => 1,
                'product_category_id' => 1,
                'price' => 799.99,
                'stock' => 50,
                'discount_id' => 1,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            
            [
                'product_id' => 11,
                'name' => 'T-shirt',
                'description' => 'Cotton T-shirt',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 2,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 12,
                'name' => 'Polo Shirt',
                'description' => 'Cotton Polo Shirt',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 2,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 13,
                'name' => 'Denim Jeans',
                'description' => 'Cotton Denim Jeans',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 2,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 14,
                'name' => 'Hoodie',
                'description' => 'Cotton Hoodie',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 2,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 15,
                'name' => 'Dress Shirt',
                'description' => 'Cotton Dress Shirt',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 2,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 16,
                'name' => 'Skirt',
                'description' => 'Cotton Skirt',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 2,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 17,
                'name' => 'Sweatpants',
                'description' => 'Cotton Sweatpants',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 2,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 18,
                'name' => 'Blouse',
                'description' => 'Cotton Blouse',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 2,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 19,
                'name' => 'Cargo Shorts',
                'description' => 'Cotton Cargo Shorts',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 2,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 20,
                'name' => 'Cardigan',
                'description' => 'Cotton Cardigan',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 2,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 21,
                'name' => 'Sofa Set',
                'description' => 'Cotton Sofa Set',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 3,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 22,
                'name' => 'Dining Table',
                'description' => 'Cotton Dining Table',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 3,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 23,
                'name' => 'Dining Table',
                'description' => 'Cotton Dining Table',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 3,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 24,
                'name' => 'Coffee Table',
                'description' => 'Cotton Coffee Table',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 3,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 25,
                'name' => 'Wardrobe',
                'description' => 'Cotton Wardrobe',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 3,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 26,
                'name' => 'Bookshelf',
                'description' => 'Cotton Bookshelf',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 3,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 27,
                'name' => 'Recliner Chair',
                'description' => 'Cotton Recliner Chair',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 3,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 28,
                'name' => 'Office Desk',
                'description' => 'Cotton Office Desk',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 3,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 29,
                'name' => 'Bar Stools',
                'description' => 'Cotton Bar Stools',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 3,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            [
                'product_id' => 30,
                'name' => 'Dresser',
                'description' => 'Cotton Dresser',
                'color_id' => 2,
                'size_id' => 2,
                'created_by_user_id' => 2,
                'product_brand_id' => 2,
                'product_category_id' => 3,
                'price' => 19.99,
                'stock' => 100,
                'discount_id' => 2,
                'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
                'deleted_at'=>Carbon::now('Asia/Ho_Chi_Minh'),
            ],
            // Thêm các dòng dữ liệu khác nếu cần
        ]);

        // Thêm dữ liệu vào các bảng khác ở đây (nếu cần)
    }
}
